### ISSUE TITLE
SIT Server Mod cannot load load "ws" dependencies

### ISSUE THREAD

**Issue by DPrison** [paulov-t/SIT.Core#38]
I idk how to write issue to mod repo, so i write this. If i start spt server with server mod, server couldn't loads and except next error: 
The application had a critical error and failed to run
Exception produced: Error: Cannot find module 'ws'
I already try to recompile spt aki server, add dependencies to mod
![image](https://github.com/paulov-t/SIT.Core/assets/62451660/2590f992-8a87-4162-85d5-c12df260bc7d)

**Comment by ppyLEK** [comment]
If I am not mistaken you need to install nodejs and run `npm install ws` to the SIT.Aki-Server-Mod-master folder from cmd.

**Comment by DPrison** [comment]
> If I am not mistaken you need to install nodejs and run `npm install ws` to the SIT.Aki-Server-Mod-master folder from cmd.

il already try, with and without -g parametr, still doesn't works

**Comment by harmonyzt** [comment]
You gotta create `node_modules` folder in src folder of SIT Server mod and then open `cmd` or `shell` in that folder to install `ws`.

**Comment by pitAlex** [comment]
@paulov-t  you forgot to add "ws" to package.json dependency.
@DPrison do npm install ws -save at the root of the mod's folder (where package.json) is. 

I wish I would help with this, but I am very constrained by time right now. I do recommend further improving the WebSocket server by using socket.io. I made you an example of how to load it up :
https://pastebin.com/xpQC9gcC  - WebSoketHandler example
https://pastebin.com/73PKuyWx  - How to give it the main AKI server as the "http.Server" it needs for initialization, you could even replace it with yours, but you would have to handle existing things that AKI expects the ws server to do.
Now this requires reading documentation:
https://socket.io/docs/v4/server-initialization/
https://github.com/doghappy/socket.io-client-csharp
But this thing handles parsing data so you do not have to worry about JSON.stringify and such,  and it can do specific events, instead of just "on message". So you could have a "spawn" event, "ondeath", "ondamage" etc..

**Comment by SlejmUr** [comment]
Websocket-Sharp used and probably a prior to it because it is exist in tarkov folder and don't need another dependency

**Comment by DPrison** [comment]
> 

Thanks, its works
